#!/bin/bash
#SBATCH --job-name=WSe2
#SBATCH -n 18
#SBATCH -t 16:00:00
#SBATCH -p shared
#SBATCH --mem-per-cpu=5000
#SBATCH -o job_%j.out
#SBATCH -e job_%j.err

module list

source activate $HOME/anaconda_env
STR="codes/ml-ph/testfiles/AAGr2/"
ALLEGRO_DIR="/n/home04/jzlu/codes/ml-ph/ALLEGRO_ANALYZER"
echo "...It's alive!! Root batch file starting."
python3 $ALLEGRO_DIR/start.py ~/$STR F Gamma eleband eledos energies phband phdos

echo "Root batch file completed execution."
mv ./job_* ~/$STR
