#!/bin/bash
#SBATCH --job-name=config_test
#SBATCH -n 12
#SBATCH -t 04:00:00
#SBATCH -p test
#SBATCH --mem-per-cpu=5000
#SBATCH -o Job%j.out
#SBATCH -e Err%j.err

module list

source activate $HOME/anaconda_env
THIS_DIR="codes/ml-ph/practice_files/config-practice/TBLG"
ALLEGRO_DIR="/n/home04/jzlu/codes/ml-ph/ALLEGRO_ANALYZER"
echo "[==ROOT BATCH FILE==] ...It's alive!! Root batch file starting."
python3 $ALLEGRO_DIR/start.py 1 ~/$THIS_DIR F Gamma energies

echo "[==ROOT BATCH FILE==] Root batch file completed execution."
