#!/bin/bash
#SBATCH --job-name=gr
#SBATCH -n 4 # Number of cores requested
#SBATCH -t 1:00:00 # Runtime in minutes
#SBATCH -p shared,test # Partition to submit to
#SBATCH --mem-per-cpu=5000 # Memory per cpu in MB (see also--mem)
#SBATCH -o job_%j.out # Standard out goes to this file
#SBATCH -e job_%j.err # Standard err goes to this file

module list

source activate $HOME/anaconda_env

for i in $(seq 0.15 0.005 0.25); do
cat >POSCAR <<END
C2_bilayer
1.0
2.130000 -1.229756 0.000000
2.130000 1.229756 0.000000
0.000000 0.000000 20.000000
C
4
direct
0.000000 0.000000 0.000000 C
0.333333 0.333333 0.000000 C
0.000000 0.000000 $i C
0.333333 0.333333 $i C
END

echo "a= $i"
mpirun -np $SLURM_NTASKS /n/kaxiras_lab/vasp/vasp.std
E=`tail -1 OSZICAR` ; echo $i $E >>SUMMARY.acell
cp OUTCAR OUTCAR-$i
cp OSZICAR OSZICAR-$i
done
cat SUMMARY.acell
