#!/bin/bash
#SBATCH --job-name=gr
#SBATCH -n 1 # Number of cores requested
#SBATCH -t 8:00:00 # Runtime in minutes
#SBATCH -p shared,test # Partition to submit to
#SBATCH --mem-per-cpu=5000 # Memory per cpu in MB (see also--mem)
#SBATCH -o job.out # Standard out goes to this file
#SBATCH -e job.err # Standard err goes to this file

echo $(ls)
