#!/bin/bash
#SBATCH --job-name=gr
#SBATCH -n 36 # Number of cores requested
#SBATCH -t 4:00:00 # Runtime in minutes
#SBATCH -p shared,test # Partition to submit to
#SBATCH --mem-per-cpu=5000 # Memory per cpu in MB (see also--mem)
#SBATCH -o job_%j.out # Standard out goes to this file
#SBATCH -e job_%j.err # Standard err goes to this file

module list

source activate $HOME/anaconda_env

mpirun -np $SLURM_NTASKS /n/kaxiras_lab/vasp/vasp.std

