#!/bin/bash
#SBATCH -J elastic
#SBATCH -n 16 # number of cores
#SBATCH -t 8:00:00 # runtime 
#SBATCH -p kaxiras,shared
#SBATCH --mem-per-cpu=4000 
#SBATCH -o elastic_%a_%A.out 
#SBATCH -e er_elastic_%a_%A.err


module load intel/17.0.4-fasrc01
module load impi/2017.2.174-fasrc01
module load python
module list

export TASKID=$SLURM_ARRAY_TASK_ID

echo "Task ID: " $TASKID
python run_vasp.py $TASKID
